package com.qa.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * POJO (Plain Old Java Object) class for User Represents user data structure
 * for API requests and responses
 * 
 * Jackson annotations used:
 * 
 * @JsonInclude - Controls serialization of null fields
 * @JsonProperty - Maps Java field to JSON field (if names differ)
 */
@JsonInclude(JsonInclude.Include.NON_NULL) // Don't serialize null fields
public class Users {

	// Request fields (what we send)
	private String name;
	private String job;

	// Response fields (what API returns)
	private String id;
	private String createdAt; // For POST response
	private String updatedAt; // For PUT response

	/**
	 * Default no-argument constructor Required by Jackson for deserialization (JSON
	 * -> Object)
	 */
	public Users() {
	}

	/**
	 * Parameterized constructor for easy object creation Used when creating request
	 * payloads
	 * 
	 * @param name - User's name
	 * @param job  - User's job title
	 */
	public Users(String name, String job) {
		this.name = name;
		this.job = job;
	}

	/**
	 * Full constructor with all fields Useful for testing
	 */
	public Users(String name, String job, String id, String createdAt, String updatedAt) {
		this.name = name;
		this.job = job;
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	// ============ GETTERS AND SETTERS ============
	// Required by Jackson for serialization/deserialization

	/**
	 * Get user's name
	 * 
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * Set user's name
	 * 
	 * @param name - User's name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get user's job
	 * 
	 * @return job title
	 */
	public String getJob() {
		return job;
	}

	/**
	 * Set user's job
	 * 
	 * @param job - Job title
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * Get user's ID
	 * 
	 * @return user ID (generated by server)
	 */
	public String getId() {
		return id;
	}

	/**
	 * Set user's ID
	 * 
	 * @param id - User ID
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get creation timestamp
	 * 
	 * @return ISO 8601 timestamp
	 */
	public String getCreatedAt() {
		return createdAt;
	}

	/**
	 * Set creation timestamp
	 * 
	 * @param createdAt - Creation timestamp
	 */
	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * Get last update timestamp
	 * 
	 * @return ISO 8601 timestamp
	 */
	public String getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * Set last update timestamp
	 * 
	 * @param updatedAt - Update timestamp
	 */
	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	// ============ UTILITY METHODS ============

	/**
	 * String representation of Users object Useful for logging and debugging
	 * 
	 * @return String representation
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Users{");
		sb.append("name='").append(name).append('\'');
		sb.append(", job='").append(job).append('\'');
		if (id != null) {
			sb.append(", id='").append(id).append('\'');
		}
		if (createdAt != null) {
			sb.append(", createdAt='").append(createdAt).append('\'');
		}
		if (updatedAt != null) {
			sb.append(", updatedAt='").append(updatedAt).append('\'');
		}
		sb.append('}');
		return sb.toString();
	}

	/**
	 * Check if two Users objects are equal Compares based on name and job only
	 * 
	 * @param obj - Object to compare
	 * @return true if equal, false otherwise
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null || getClass() != obj.getClass())
			return false;

		Users users = (Users) obj;

		if (name != null ? !name.equals(users.name) : users.name != null)
			return false;
		return job != null ? job.equals(users.job) : users.job == null;
	}

	/**
	 * Generate hash code Based on name and job
	 * 
	 * @return hash code
	 */
	@Override
	public int hashCode() {
		int result = name != null ? name.hashCode() : 0;
		result = 31 * result + (job != null ? job.hashCode() : 0);
		return result;
	}

	/**
	 * Validate user data
	 * 
	 * @return true if valid, false otherwise
	 */
	public boolean isValid() {
		return name != null && !name.trim().isEmpty() && job != null && !job.trim().isEmpty();
	}
}